### ISSUE TITLE
halting due to 403 error

### ISSUE THREAD

**Issue by joshuachris2001** [iiEpic/wco-dl#27]
I'm trying to download some shows and on start it states `downloading show`
but nothing happens. I tried verbose and I get DEBUG: https://www.wcostream.com:443 "GET /show/name HTTP/1.1" 403 None

**Comment by BackToTheThe** [comment]
I'm having the same problem. Here is my error log:

```
DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(version=False, input=['https://www.wcostream.com/xxxx/yyyy'], highdef=False, episoderange='All', season='All', exclude=None, output=None, verbose=True)
DEBUG: Operating System : Linux - 5.13.0-52-generic - #59-Ubuntu SMP Wed Jun 15 20:17:13 UTC 2022
DEBUG: Python Version : 3.9.7 (64bit)
DEBUG: Starting new HTTPS connection (1): www.wcostream.com:443
DEBUG: https://www.wcostream.com:443 "GET /xxxx/yyyy HTTP/1.1" 403 None
```

The values of "xxxx" and "yyyy" are irrelevant, this happens every time, for every URL that's passed in.

**Comment by gwarakgames** [comment]
I got around this by changing the Python libraries used to urllib and supplying a user agent
