### ISSUE TITLE
New Website URL

### ISSUE THREAD

**Issue by dakonut44** [iiEpic/wco-dl#33]
Hey, the wcostream website now redirects to .tv no matter what you enter in, so the script is getting 403 errors again. I tried to update it myself but I don't really know how. 

The new url is https://www.wcostream.tv/

**Comment by MatthewRasa** [comment]
@dakonut44 I opened up a PR to fix this, but not sure if/when it will be merged. Feel free to pull the latest from my fork if you want to try it out in the meanwhile: https://github.com/MatthewRasa/wco-dl/tree/master
